### ISSUE TITLE
How to get deployment/daemonset/job name in  log source  "Kubernetes Container Generic Logs"

### ISSUE THREAD

**Issue by gao4263** [oracle-quickstart/oci-kubernetes-monitoring#63]
![image](https://github.com/oracle-quickstart/oci-kubernetes-monitoring/assets/4172582/ce90b2c6-1906-4efc-b711-d882fcdc68b4)

customer want explore log in specified deployment.

**Comment by santhoshkvuda** [comment]
At present we have only support for pod/namespace/node as additional metadata to the pod logs. you may use pod name attached to the logs to derive corresponding workload name as the first part of the pod name is typically the name of the workload in general.
