### ISSUE TITLE
Documentation: dashboard import command missing option --dashboard

### ISSUE THREAD

**Issue by aboncok** [oracle-quickstart/oci-kubernetes-monitoring#64]
Hi,
In the README when copying and trying to run a dashboard import, the oci cli returns with the following error:
```
Usage: oci management-dashboard dashboard import [OPTIONS]

Error: Missing option(s) --dashboards.
```

**Comment by aboncok** [comment]
Cause: json file was in incorrect format.

**Comment by santhoshkvuda** [comment]
@paliwalparitosh , please check

**Comment by paliwalparitosh** [comment]
@aboncok did you execute `sed` command prior to dashboard import command? 

- `<Replace-with-Compartment-OCID>` should be the target compartment OCID.

- `sed -i "s/\${compartment_ocid}/<Replace-with-Compartment-OCID>/g" *.json`

- I validated the commands today and was able to import all 5 dashboards.

![image](https://github.com/oracle-quickstart/oci-kubernetes-monitoring/assets/8281625/a2874712-d439-4741-90b2-c78556160fdb)

![image](https://github.com/oracle-quickstart/oci-kubernetes-monitoring/assets/8281625/529cb3c0-c622-4ede-b878-48c1da5d7391)

**Comment by aboncok** [comment]
@paliwalparitosh I didn't elaborate in my additional comment.
The command is working when a properly formatted json is supplied. However, if it's not a properly formatted json file then that error message is received which does not tell that the issue is the json file.

As such the problem is that the error message is misleading but that might not be an issue with this project, instead it belongs to whoever developed the API/CLI.

My mistake was that I downloaded the json by right clicking the link and it resulted in an invalid format.

**Comment by paliwalparitosh** [comment]
The reported issues is not in scope of k8s monitoring solution but related to OCI CLI.
