### ISSUE TITLE
discovery cronjob is failing to start

### ISSUE THREAD

**Issue by sourabhgupta385** [oracle-quickstart/oci-kubernetes-monitoring#73]
Hi Team,

I've built the docker image using exact same files from https://github.com/oracle-quickstart/oci-kubernetes-monitoring/tree/v3.3.0/logan/docker-images/v1.0/oraclelinux/8-slim . But when the helm chart is deployed, oci-onm-logan pods works fine but  oci-onm-discovery pods fails with below logs - 

```
k logs -f oci-onm-discovery-28545505-6s6x5
bundler: command not found: oci-loganalytics-kubernetes-discovery
Install missing gem executables with `bundle install`
```

Can you please help us on this?

Regards,
Sourabh

**Comment by santhoshkvuda** [comment]
hi @sourabhgupta385 , we will fix this soon. Meanwhile, could you try adding the following to Gemfile.

gem "oci-logging-analytics-kubernetes-discovery", "1.0.0"

**Comment by sourabhgupta385** [comment]
Sure, Thank you @santhoshkvuda

**Comment by santhoshkvuda** [comment]
This is fixed now.
