### ISSUE TITLE
Documentation: OCI_TENANCY_NAMESPACE

### ISSUE THREAD

**Issue by karpa13st** [oracle-quickstart/oci-kubernetes-monitoring#9]
Greetings!
please clarify: what OCI_TENANCY_NAMESPACE config option is mean? tenancy name?
how to debug that the installation is working well?
i followed the installation instructions:
1. turn on LA in the region
2. create LogGroups
3. enable access via dyn groups.
4. build a docker image based on Debian. upload to OCIR
5. prepared fluentd-daemonset.yaml file (update <IMAGE_URL>, <OCI_LOGGING_ANALYTICS_LOG_GROUP_ID>, <OCI_TENANCY_NAMESPACE>, <KUBERNETES_CLUSTER_OCID>,<KUBERNETES_CLUSTER_NAME>)
6. deployed to test OKE cluster (using configmap-cri.yaml and fluentd-daemonset.yaml Logs collection) 

unfortunately, no logs arrive in Log explorer in Logging analytics
some steps missed?

**Comment by santhoshkvuda** [comment]
Thanks @karpa13st for reaching out to us. First of all, you seems to be using Kubectl based approach but we would recommend to use helm chart based installation. Still, kubectl based installation should work for you and to help you in triaging the actual issue, we may need the following information :

- To verify that the daemonset, configMap and other resources have been successfully installed, run the following commands and validate the output. Ensure the pods are in running state. 

  `kubectl get configmaps -n <namespace>`

  `kubectl get daemonsets -n <namespace>`

  `kubectl get pods -n <namespace>`

- Verify the daemonset pod logs using following command and check if fluentd worker is started successfully or not. If you identify any errors/exceptions, please post them here.

  `kubectl logs <daemonset pod name> -n <namespace>`

  ```
  2022-08-18 10:34:31 +0000 [info]: #0 starting fluentd worker pid=<> ppid=<> worker=0
  2022-08-18 10:35:06 +0000 [info]: #0 fluentd worker is now running worker=0
  ```
- The LA fluentd output plugin logs are available at /var/log/oci-logging-analytics.log (default location) on every Daemonset pod (mounted to the host too at the same location). Please verify if there are any errors/exceptions logged in the log and if yes, kindly share the whole log file.

- Regarding OCI_TENANCY_NAMESPACE, it is OCI Tenancy namespace which you may find using the following approach.
  - Go to Logging Analytics Administration, click Service Details, and find the namespace value using Service Namespace field.

- You may also try this step by step guide using [Oracle LiveLab Workshop](https://apexapps.oracle.com/pls/apex/r/dbpm/livelabs/view-workshop?wid=3348) to get started with this.

**Comment by karpa13st** [comment]
Greetings!

Thank you @santhoshkvuda !

>Go to Logging Analytics Administration, click Service Details, and find the namespace value using Service Namespace field.

this solved my issue. logs have arrived at Logging Analytics
please, update the docs)
